# Set to true to enable caching of Entry elements in the Repository.
cachingEntryCollector=true

# Time in milliseconds that a call to a missing <pen:bean> will block before failing. Bean Dampening can be turned off
# by setting this value to -1
dampening-timeout=10000

# By default default content will load Asynchronously on server start. To block server availability until all
# default content is loaded, set this value to "false"
enable-async-default-content-loading=true

# Set to false to disable caching of domain information
# enableDomainIdCache = false

# Whether or not to hide the user home folder on user creation
hideUserHomeFolderOnCreate=false

# Default folder to open or save file(s) in case user's home folder is hidden
defaultFolderWhenHomeFolderIsHidden=/public

## CSRF ##

# Enables CSRF (Cross-Site Request Forgery) protection for the server.
# - Defaults to `true`.
#
# *ATTENTION*:
# Setting this option to `false` opens the server and all of its plugins to known security flaws,
# which can allow an attacker to perform CSRF attacks.
#
# Do NOT set this option to `false`, if at all possible. Instead, consider disabling CSRF protection selectively,
# for certain platform plugins or for certain endpoints. This may be necessary if there still exists external code
# which depends on the unprotected and deprecated APIs.
#
# To disable CSRF protection for a plugin, in its `plugin.spring.xml` file, look for a bean registering
# the interface `CsrfRequestSetConfiguration`, such as of the stock class `CsrfRequestSetConfigurationPojo`
# and any accompanying documentation.
# To disable all endpoints, commenting out the whole bean declaration should suffice.
# To disable protection for certain endpoints, comment the corresponding `*-request-matcher` element.
#
# To disable CSRF protection for a certain server endpoint,
# in the file `system/applicationContext-spring-security-csrf.xml`,
# find the bean of class `CsrfRequestSetConfigurationPojo` and comment the corresponding `*-request-matcher` element.
csrf-protection-enabled=true

## CORS ##

# For general information about CORS, please see: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS.

# ## Activating Cross-Site/Embedding use on the Pentaho Server
#
# Several settings must be changed:
#
# 1. In this file,
#    set the property `cors-requests-allowed` to `true`;
#    additionally, configure the trusted (cross) sites, in the property `cors-requests-allowed-domains`.
#    Example:
#
#    cors-requests-allowed=true
#    cors-requests-allowed-domains=https://trusted-domain-1.com,https://trusted-domain-2.com
#
# 2. In `webapps/pentaho/WEB-INF/web.xml`,
#    ensure that the element `/web-app/session-config/cookie-config/secure` exists and its value is `true`.
#    Example:
#
#    <web-app>
#      ...
#      <session-config>
#        ...
#        <cookie-config>
#          ...
#          <secure>true</secure>
#        </cookie-config>
#      </session-config>
#    </web-app>
#
# 3. If Pentaho is installed on the Tomcat application container,
#    in `tomcat/conf/context.xml`,
#    ensure the element `/Context/CookieProcessor` exists and the attribute `sameSiteCookies` has the value `None`.
#    Example:
#
#    <Context>
#      ...
#      <CookieProcessor sameSiteCookies="None"
#                       className="org.apache.tomcat.util.http.LegacyCookieProcessor" />
#    </Context>

# Enable cross-origin HTTP requests.
# - Defaults to `false`.
# - Enables cross-origin requests for all URLs served by the Pentaho Server,
#   unless overridden in a child CORS configuration (see `cors-root-config-is-abstract`).
# - Commented out to give precedence to same-named legacy option in `pentaho.xml`.
#cors-requests-allowed=false

# External origins which can call this server.
# - Comma-separated list of values.
# - Origins are constituted by the URL components: protocol, host and port.
# - Origins are compared case-insensitively.
# - Ports are defaulted according to the protocol (e.g. default port for the http protocol is 80).
# - Example: https://domainA.com, https://localhost:1337
# - More information: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin
# - Commented out to give precedence to same-named legacy option in `pentaho.xml`.
#cors-requests-allowed-domains=

# Allowed HTTP request methods.
# - Comma-separated list of values.
# - More information: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Methods
cors-requests-allowed-methods=GET,HEAD,POST

# Allowed HTTP request headers.
# - CRSF protection requires the headers: CONTENT-TYPE and X-CSRF-TOKEN.
# - More information: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Headers
cors-requests-allowed-headers=CONTENT-TYPE,X-CSRF-TOKEN

# Allow credentials to be included in requests?
# - CSRF protection requires credentials being provided.
# - More information: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Credentials
cors-requests-allow-credentials=true

# HTTP response headers that can be read by JavaScript code at the web client.
# - Comma-separated list of values.
# - More information: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers
cors-requests-exposed-headers=

# (Advanced) Indicates that the top-level CORS configuration is "abstract".
# - The default value is `false`.
# - When `false`, all URLs allow CORS as long as `cors-requests-allowed` is `true`.
# - Abstract CORS configurations serve only to provide default values for their child CORS configurations.
# - Child CORS configurations apply to a certain base context URL and must be enabled explicitly to
#   allow CORS for the covered URLs.
# - Any URL not covered by an enabled (non-abstract) child CORS configuration will not allow CORS requests.
# - While the "abstract root" mode provides more control over which URLs actually allow CORS requests,
#   that is achieved at the expense of additional configuration.
# - Child CORS configurations can be defined using Spring beans.
cors-root-config-is-abstract=false
